apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
      - name: devops-backend
        image: docker.io/gopu108/backend-assignment:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: bakcend-service
spec:
  selector:
    app: devops-backend
  ports:
  - port: 8000
    targetPort: 8000
