apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frondtend
spec:
  selector:
    matchLabels:
      app: devops-frondtend
  template:
    metadata:
      labels:
        app: devops-frondtend
    spec:
      containers:
      - name: devops-frondtend
        image: docker.io/gopu108/frontend-assignment:latest
        env:
        - name: BACKEND_URL
          value: http://bakcend-service:8000
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: devops-frondtend
  ports:
  - port: 3000
    targetPort: 3000

